//Обработка ошибок


// try {
//     console.log(1);
//     console.log(2);
//     const user ={};
//     console.log(user.name.er);
    // if (!user.name){
    //     throw new SyntaxError('Ошибка')
    // }
// } catch (error) {
//     console.log("я допустил ошибку")
//     console.log(error.name)
//     console.log(error.message)
    // console.log("error", error);
// } finally {
//     console.log("Я попал в finaly")
// }

// console.log(4)